version: '3.9'

services:
  azuredevopsjanitor.host.eventforwarder:
    image: azure-devops-janitor-event-forwarder
    build:
      context: .
      dockerfile: src/AzureDevOpsJanitor.Host.EventForwarder/Dockerfile